### ISSUE TITLE
"bad" observation error estimates

### ISSUE THREAD

**Issue by kalebentley** [mdscheuerell/chumIPM#11]
I wanted to create a thread to further the discussion regarding "bad estimates of observation error".  This topic was flagged by @ebuhle in a previous post [here](https://github.com/mdscheuerell/chumIPM/issues/9#issuecomment-821758916).  

In short, are there any estimates of precision for either spawners and/or smolts that are biased (i.e., overly precise)?  While I can't really speak to the estimates of precision for spawners, we are all aware of the fact that there are juveniles estimates of abundance where the uncertainty is underestimated due to expansions of count data via weight or volumetric sub-sampling.  

With help from our database group (Tiffany and Danny), I pulled together some information to hopefully help us assess how much this sub-sampling could be leading to underestimates of precision.  I've uploaded a file with some more information into our IPM data folder.

Here's a quick summary of juvenile estimates that were generated (by site and year) where at least a portion of the total estimate was generated using sub-sampling:

![image](https://user-images.githubusercontent.com/40397762/116943764-13c13d80-ac29-11eb-921d-d5c089d88200.png)

In some years, approximately 50% of the "observed catch" was estimated via sub-sampling (i.e., not hand-counted).  As @ebuhle, sub-sampling happened in years that were classified as "census" (meaning there was no trap outages and the estimated uncertainty is 0 currently).  However, sub-sampling also occurred in years where the total estimate was no considered a census either because there were trap outages (at Hamilton) or because the trap was not operated as a census weir (CJ and Grays -- where M-R is used).  

The file I uploaded has some of the "raw" data from the sub-sampling events from a few different years and sites.  Perhaps the next step should be to explore some of these data to see how much uncertainty there actually is in the sub-sampling.  I haven't spent much time doing this yet.  If the sub-sampling appears to be resulting in a "non-negligible" amount of uncertainty, then perhaps we discuss the best way to incorporate this uncertainty that is currently being ignored.

Thoughts?

For reference, here's how the sub-sampling works for weights (volume is fairly similar):
**Estimating Total Captures by Weight**
_Standard procedure is to individually count all fish captured.  However, it is possible to have daily catch totals of salmonid fry so large (>10,000) that it would take too long to efficiently process the daily catch if hand counted.  When this occurs, a protocol for estimating the fry portion of the daily catch via weight sampling is used.  Sub-yearling and yearling salmonids and non-salmonids are still individually counted; weight sampling is used only for maiden salmonid fry.  The protocol for weight sampling is as follows.  One hundred fry are hand counted from a random sub-sample of the days catch and weighed (tared weighing vessel that includes water).  The weight and species composition of the weight sub-sample are recorded.   This is followed by a larger “bulk” group (400-500 grams worth) of fry being weighed (tared weighing vessel that includes water) and released without hand counting.  This process is repeated to account for changes in species composition or size that may occur over the course of measuring out the entire daily fry catch.  The average fry weight and species composition of the sub-samples are then used to expand the un-counted samples.  This method can hypothetically result in missing rare salmonid fry within the bulk samples.  However, this is the best procedure we have been able to implement.   A more detailed explanation of the formulas used to convert the weight sampling data to daily fry estimates and their variances is detailed in the Production Protocol.  To minimize the amount of water in a sample, fry are netted from holding buckets using small mesh nets and water is allowed to drain and is wiped by hand from the net.  Since it is impossible to completely remove all water without causing mortality, consistent water removal actions are done in an effort to make the amount of water in each sample as consistent as possible._

**Comment by Hillsont** [comment]
I can't speak much about uncertainty in the volumetric sampling beyond Dan looked at back when we started using this method and was satisfied with the results.  I understand this is a deeper dive into the method as a result of a new use of the results and I'm supportive.  The raw data from the early years, before Danny built in the calculations into the JMX front end, will need to be transcribed from scanned data sheets.

Tiffany called me when she was tracking things down and I sent her files that included the raw data for when the bulk weight method was used at Hamilton Springs so that will be easier to pull together.  I didn't do it for every year but below is a snip of the 2012 summary for bulk weight sampling that season.  Estimates of uncertainty came from R code Dan wrote for me, pasted below in case that helps.  Estimates of variance were generated using the 2.5 and 97.5 credible intervals assuming a normal distribution. 

![image](https://user-images.githubusercontent.com/68036398/116948140-7ae3ef80-ac33-11eb-8329-29cf4cc7e99a.png)
  

rm(list=ls(all=TRUE))
library(R2WinBUGS)    # Load the R2WinBUGS library
setwd('C:/data/Chum/Floy tagging/Winbugs R Studio and R files and notes/WinBUGS working files')


# Save BUGS description of the model to working directory
sink("model.txt")
cat("
Model{
  for ( i in 1:samps) {
    y[i] ~dnorm(mu,tau)}
  
  mu~ dnorm(0,0.000001)
  tau~ dgamma(0.001,0.001)
  hier_count~dnorm(mu,tau)
  count <- scoops * hier_count + sum(y[])
}
",fill=TRUE)
sink()


#Load Data

win.data <-list(samps=5, scoops=5555, y=c(2.50,2.35,2.45,2.46,2.49))

# scoops = total bulk weight (grams)  y=c values are # fry per gram from sub-sampling 


#Load inits
inits<-list(list(mu=300,tau=1))

#Run Model (LOAD DATA and Inits FIRST!!!)

# Parameters to be monitored (= to estimate)
params <- c("count", "hier_count", "mu","tau")
     
  
# MCMC settings
     nc <- 1    # Number of chains
     ni <- 30000	# Number of draws from posterior (for each chain)
     nb <- 2000# Number of draws to discard as burn-in
     nt <- 1		# Thinning rate
     
     
# Start Gibbs sampler: Run model in WinBUGS and save results in object called out
     out <- bugs(
       data = win.data, 
       inits = inits, 
       parameters.to.save = params, 
       model.file = "model.txt",
       bugs.directory="C:/data/winbugs/WinBUGS14/WinBUGS14",
       program=c("WinBUGS"), 
       n.thin = nt, 
       n.chains = nc, 
       n.burnin = nb, 
       n.iter = ni, 
       debug = FALSE, 
       DIC = TRUE, 
       working.directory = getwd())
     
     print(out, dig=3)	# Produces a summary of the object
     
     ls()
     
     names(out)
     
     str(out)

**Comment by ebuhle** [comment]
Thanks, this is great! (And thanks to Tiffany and Danny.) I took a quick look at the `Subsample summaries` tab; I might need a bit of data-dictionary help with the raw data, but I think I mostly get it.

Dan's model seems pretty reasonable, although I would set it up a bit differently -- I think of subsample weight as being the observation rather than fry/g, and I would use a lognormal likelihood and priors more in line with current [best practices](https://mc-stan.org/users/documentation/case-studies/weakly_informative_shapes.html). It also doesn't seem to address the species composition (for which one could use a multinomial likelihood) or the suggestion that systematic changes may occur over the course of sampling:

> his process is repeated to account for changes in species composition or size that may occur over the course of measuring out the entire daily fry catch. The average fry weight and species composition of the sub-samples are then used to expand the un-counted samples.

Still, I'm sure it's fine, especially if an update would require entering scanned raw data. I'm confused, though, because the uncertainty estimates don't seem to be included in the juvenile data (e.g., the census years with 0% CV). Am I missing something?

On another note, re the table in the OP, I worry a little about using multi-year hierarchical models to summarize "raw" sample-based estimates from individual years. Depending on how much information is shared across years or "borrowed" to inform data-poor years, this amounts to a form of smoothing based on a statistical model before the output is subjected to further smoothing based on a population-dynamics model (ours or any other). You can imagine how this might induce spurious precision and correlation in observations that the pop-dyn model assumes to be independent. Maybe NBD in practice, I don't know, but another thing to think about.

**Comment by Hillsont** [comment]
> Dan's model seems pretty reasonable, although I would set it up a bit differently -- I think of subsample weight as being the observation rather than fry/g, and I would use a lognormal likelihood and priors more in line with current [best practices](https://mc-stan.org/users/documentation/case-studies/weakly_informative_shapes.html). It also doesn't seem to address the species composition (for which one could use a multinomial likelihood) or the suggestion that systematic changes may occur over the course of sampling:
> > This process is repeated to account for changes in species composition or size that may occur over the course of measuring out the entire daily fry catch. The average fry weight and species composition of the sub-samples are then used to expand the un-counted samples.
> 
Sounds like our code needs some updating but it hasn’t been used since Danny built in the math to the JMX frontend.  Which means we do not have estimates of uncertainty since he did that.  Also, at Hamilton Springs the fry are pretty “clean” (very few non-chum fry are captured) and the staff actively try and remove any non-chum fry from the bulk weight samples.     
> I'm also not sure how we wind up with a CV of the total (0.0086) that is lower than all but 3 of the individual expansion estimates. I suspect this comes from assuming a normal likelihood instead of lognormal, in which case the variance would scale with the mean (as it should).
> 
The uncertainty in the 2012 Total lines was simply done by adding the daily variances and re-calcing the SE assuming normal distribution.  That may be the reason they look “off”. 
> That said, it would take a pretty compelling alternative to be worth entering scanned raw data. And then, I assume, the updated estimates would have to be run through BTSPAS or whatever in the non-"census" years, right?
> 
@ebuhle & @kalebentley Maybe a look at one year in CJ when the data is in Access instead of on paper data sheets?  I know there’s a lot more variability in the species comp at CJ.
>
> I'm confused, though, because the uncertainty estimates don't seem to be included in the juvenile data (e.g., the "census" years with 0% CV). Am I missing something?
> 
@ebuhle, your not.  It’s was an oversight on our part.  I’m guessing the census years with bulk weight sampling days are not going to be a big lift to deal with.  However, the analysis method we use to account for missed days at weirs (p-spline code Dan wrote) doesn’t have the ability to incorporate the uncertainty from the bulk weight sampling.  I can’t guess at the effort it would take to add that feature.

**Comment by kalebentley** [comment]
> Thanks, this is great! (And thanks to Tiffany and Danny.) I took a quick look at the `Subsample summaries` tab; I might need a bit of data-dictionary help with the raw data, but I think I mostly get it.

Let me know if there is anything that would be useful to go over.  It was my best attempt at trying to get a handle on the potential unexplained sampling variation but admittedly it is a bit of a jumbled mess.

> I'm also not sure how we wind up with a CV of the total (0.0086) that is lower than all but 3 of the individual expansion estimates. I suspect this comes from assuming a normal likelihood instead of lognormal, in which case the variance would scale with the mean (as it should).

Not sure if this is affected by the distribution or rather the result of the pooled variances.
 
> That said, it would take a pretty compelling alternative to be worth entering scanned raw data. And then, I assume, the updated estimates would have to be run through BTSPAS or whatever in the non-"census" years, right?

Right now, the sub-sampling variance is NOT incorporated into any estimate whether the analysis was completed with a "census", p-spline, BTSPAS or the multi-year ARIMA model.  I hadn't ever seen the WinBUGS code Todd shared above but I suppose in theory something like Dan's model could be incorporated into all of the abundance models.  However, this would require some work and I'm not entirely sure it would be possible for BTSPAS, which is an [R package](https://cran.r-project.org/web/packages/BTSPAS/BTSPAS.pdf) and I don't believe the inputs can be anything but counts.

> I'm confused, though, because the uncertainty estimates don't seem to be included in the juvenile data (e.g., the "census" years with 0% CV). Am I missing something?

My guess is that even in "census" years (i.e., no trap outages), the sub-sampling error was ignored (i.e., Dan's WinBUGS model was not run).

> On another note, re the table in the OP, I worry a little about using multi-year hierarchical models to summarize "raw" sample-based estimates from individual years. Depending on how much information is shared across years or "borrowed" to inform data-poor years, this amounts to a form of shrinkage based on a statistical model before the output is subjected to further shrinkage based on a population-dynamics model (ours or any other). You can imagine how this might induce spurious precision and correlation in observations that the pop-dyn model assumes to be independent. Maybe NBD in practice, I don't know, but another thing to think about.

I think I follow your logic.  @tbuehrens developed two multi-year ARIMA models last year (one for count data and one for estimates with observation error) to deal with years when a "good chunk" of the outmigration was missed/not sampled (call them "bad years").  I get that we could omit these years and let the IPM estimate the juvenile abundance, which would potentially negate the concern over "spurious precision".  However, one draw back is that we would be losing some of the information that was contained in the data that were collected in the "bad years".  Overall, there's only a couple of juvenile estimates that this would impact (Duncan and Hamilton in outmigration years 2017 and 2020 -- currently Duncan 2017 is entered as NA).

**Comment by ebuhle** [comment]
> Right now, the sub-sampling variance is NOT incorporated into any estimate whether the analysis was completed with a "census", p-spline, BTSPAS or the multi-year ARIMA model.

> My guess is that even in "census" years (i.e., no trap outages), the sub-sampling error was ignored (i.e., Dan's WinBUGS model was not run).

Ah, I see. So we have a method to quantify and propagate subsampling uncertainty, but it hasn't actually been applied to the estimates we're using. Or maybe it has, but only in "early" years?

> Sounds like our code needs some updating but it hasn’t been used since Danny built in the math to the JMX frontend. Which means we do not have estimates of uncertainty since he did that.

Regardless, @kalebentley is right that we would need to tweak the models used to smooth / interpolate the annual counts. Likewise, I gather the M-R uncertainties at the Grays traps are not currently propagated through the BTSPAS or P-spline interpolation models.

> Right now, the sub-sampling variance is NOT incorporated into any estimate whether the analysis was completed with a "census", p-spline, BTSPAS or the multi-year ARIMA model. I hadn't ever seen the WinBUGS code Todd shared above but I suppose in theory something like Dan's model could be incorporated into all of the abundance models. However, this would require some work and I'm not entirely sure it would be possible for BTSPAS, which is an [R package](https://cran.r-project.org/web/packages/BTSPAS/BTSPAS.pdf) and I don't believe the inputs can be anything but counts.

I'm involved in a [UW grad student project](https://github.com/marksorel8/Wenatchee-screw-traps) that is developing home-brewed models to do something similar to BTSPAS et al., so that might provide a jumping-off point. This would obviously be a nontrivial effort, though, and I don't want to get too far out of my lane here. I think the next step, as you guys are suggesting, is to try an alternative model for the sample data @kalebentley provided and see (1) how much the uncertainty estimates differ from Dan's model and (2) how large the omitted subsampling errors are compared to the other, currently reported errors.

> Not sure if this is affected by the distribution or rather the result of the pooled variances.

Yeah, you're right, the CV of a sum of *K* RVs scales roughly as 1/sqrt(*K*). I still find the use of the normal unsettling, though it may not matter much when the CV is ≲ 0.1. If this example is typical, it looks like the combined CV is dwarfed by M-R and/or interpolation error in all but a few years, so this may all be moot. That said, given the workflow outlined above, the uncertainty of the daily estimates would be propagated through the interpolation model (in non-"census" years) before they were summed, so it might matter more than the CV of the sum would suggest. 

> I think I follow your logic. @tbuehrens developed two multi-year ARIMA models last year (one for count data and one for estimates with observation error) to deal with years when a "good chunk" of the outmigration was missed/not sampled (call them "bad years"). I get that we could omit these years and let the IPM estimate the juvenile abundance, which would potentially negate the concern over "spurious precision". However, one draw back is that we would be losing some of the information that was contained in the data that were collected in the "bad years". Overall, there's only a couple of juvenile estimates that this would impact (Duncan and Hamilton in outmigration years 2017 and 2020 -- currently Duncan 2017 is entered as NA).

Right, I generally like this approach; in fact I did something similar years ago, which was eventually absorbed into the aforementioned SAFS PhD project. It only becomes an issue when you want to use the (nonindependent) annual estimates to fit a model. But if this really only affects two data points, it's not worth worrying about.

**Comment by tbuehrens** [comment]
@ebuhle you raise a good point about treating estimates as "data" or "observations" when they are in fact already the output of models that involve shrinkage (random effects, or even state-space multi-year structure). It is something I have thought about a bunch...all of our coho abundance estimates in the lower Columbia are in fact the product of a multivariate state space model but Eli and others treat them as "observations" for fitting their smoothing models. I do think it is something to think about but especially in this context it when it affects one or two or a small number of estimates, I'm not sure it's worth worrying about.

**Comment by ebuhle** [comment]
Yeah, @tbuehrens, I figured you would've considered this issue. We've discussed it in Mark Sorel's Wenatchee project too (I'm not @-ing him because that would remind him I owe him comments on an abstract, LOL) and eventually decided *not* to partially pool years because the estimates are destined for use in an IPM. I'm not sure what the optimal solution is for reporting in general. The worst-case scenario is that [pop-dyn model output is used as pop-dyn model input](https://cdnsciencepub.com/doi/abs/10.1139/cjfas-2014-0231).

**Comment by kalebentley** [comment]
> > Right now, the sub-sampling variance is NOT incorporated into any estimate whether the analysis was completed with a "census", p-spline, BTSPAS or the multi-year ARIMA model.
> 
> > My guess is that even in "census" years (i.e., no trap outages), the sub-sampling error was ignored (i.e., Dan's WinBUGS model was not run).
> 
> Ah, I see. So we have a method to quantify and propagate subsampling uncertainty, but it hasn't actually been applied to the estimates we're using. Or maybe it has, but only in "early" years?

Yes - this is my guess.  But again, Dan's WinBUGS model only works to quantify sampling uncertainty in years with "census" data, which for Hamilton Channel has only occurred twice.  

An alternative approach to accounting for (some) sampling uncertainy would be to use the estimates of uncertainty from the "p-spline" model that are generated for all days.  Currently, (I believe) estimates of uncertainty are only included from missing trap days and assumed zero on all other days even if sub-sampling occurred.  I realize this method isn't totally transferable but it would be a pretty simple way to include some additional observation error as the model is already set up and I'm pretty sure these results could be summarized relatively quickly.  

> > Sounds like our code needs some updating but it hasn’t been used since Danny built in the math to the JMX frontend. Which means we do not have estimates of uncertainty since he did that.
> 
> Regardless, @kalebentley is right that we would need to tweak the models used to smooth / interpolate the annual counts. Likewise, I gather the M-R uncertainties at the Grays traps are not currently propagated through the BTSPAS or P-spline interpolation models.

Exactly

> > Right now, the sub-sampling variance is NOT incorporated into any estimate whether the analysis was completed with a "census", p-spline, BTSPAS or the multi-year ARIMA model. I hadn't ever seen the WinBUGS code Todd shared above but I suppose in theory something like Dan's model could be incorporated into all of the abundance models. However, this would require some work and I'm not entirely sure it would be possible for BTSPAS, which is an [R package](https://cran.r-project.org/web/packages/BTSPAS/BTSPAS.pdf) and I don't believe the inputs can be anything but counts.
> 
> I'm involved in a [UW grad student project](https://github.com/marksorel8/Wenatchee-screw-traps) that is developing home-brewed models to do something similar to BTSPAS et al., so that might provide a jumping-off point. This would obviously be a nontrivial effort, though, and I don't want to get too far out of my lane here. I think the next step, as you guys are suggesting, is to try an alternative model for the sample data @kalebentley provided and see (1) how much the uncertainty estimates differ from Dan's model and (2) how large the omitted subsampling errors are compared to the other, currently reported errors.

Good to know re: Mark Sorel's "home-brewed" models.  @tbuehrens has been talking about coding up his own BTSPAS-esk model but lower on the list of priorities given that BTSPAS is decent and better than what was being used previously.  Until something like this is done, I don't know of a way to account for sub-sampling (error) with the M-R (BTSPAS) model(s).  Again, the spline model could be updated but would take some effort and begs the question if it is worth it (at the moment) versus other options (see my comment above). 

> > Not sure if this is affected by the distribution or rather the result of the pooled variances.
> 
> Yeah, you're right, the CV of a sum of _K_ RVs scales roughly as 1/sqrt(_K_). I still find the use of the normal unsettling, though it may not matter much when the CV is ≲ 0.1. If this example is typical, it looks like the combined CV is dwarfed by M-R and/or interpolation error in all but a few years, so this may all be moot. That said, given the workflow outlined above, the uncertainty of the daily estimates would be propagated through the interpolation model (in non-"census" years) before they were summed, so it might matter more than the CV of the sum would suggest.

Good point.  
 
> > I think I follow your logic. @tbuehrens developed two multi-year ARIMA models last year (one for count data and one for estimates with observation error) to deal with years when a "good chunk" of the outmigration was missed/not sampled (call them "bad years"). I get that we could omit these years and let the IPM estimate the juvenile abundance, which would potentially negate the concern over "spurious precision". However, one draw back is that we would be losing some of the information that was contained in the data that were collected in the "bad years". Overall, there's only a couple of juvenile estimates that this would impact (Duncan and Hamilton in outmigration years 2017 and 2020 -- currently Duncan 2017 is entered as NA).
> 
> Right, I generally like this approach; in fact I did something similar years ago, which was eventually absorbed into the aforementioned SAFS PhD project. It only becomes an issue when you want to use the (nonindependent) annual estimates to fit a model. But if this really only affects two data points, it's not worth worrying about.

Currently there are three "multi-year" data points - could be four when I finally get around to trying to run our multi-year model with the 2017 Duncan dataset included.  Not sure it's worth spending much more time on this but I did want to highlight that the CVs on these three "multi-year" estimates are quite high (0.29, 0.53, and 1.89!).  

As an aside, I ran the multi-year model last week for Hamilton Springs with the 2021 outmigration dataset included (the previous estimates were run through 2020) and the 2020 estimate changed quite substantially.  The median point estimate went from 88K (CV of 0.53) to 1.1M (CV of 0.10).  There is no way this new estimate is anywhere close to reality as only 333 adults were estimated to have spawned in the channel (and the sex ratio was ~2:1 males:females).  The model likely hasn't totally converged (n_eff ~50) so these results are subject to change.  However, it does add to the conservation of whether these "multi-year" estimates should be included in our IPM data set.  And if we keep them, how do we chose which estimate to use (ignoring the any that are completely unbelievable) given that they will (likely) change annually.

**Comment by tbuehrens** [comment]
@ebuhle yes, that paper re using stock assessments as data makes the point well...for now SO MUCH of salmon parameter estimates are SO bad, that to me, this is the least of our worries...re: mark's work, I haven't seen it for years ( i think he invited me to that first meeting with you, Mark, and Sarah but none since). I have been working with other collaborators on a flexible multi-year model but it's weaknesses are: 1) is it doesn't facilitate delayed migration of marked fish, and 2) it is written in JAGS (which is definitely a weakness). I also have draft versions of a new single year model cooked up in STAN to eventually replace BTSPAS but haven't had time to fully debug them.

**Comment by tbuehrens** [comment]
a couple more thoughts: @ebuhle in short, multi-year estimates are only problematic because they are biased...they are biased toward the hypothesized underlying relationships used to relate the data among years (AR1, SARIMA, random effects, or even worst case scenario, the implied prior resulting from a full scale stock assessment!!!). But I guess my point here is that the bias (as in bias-variance tradeoff) imposed by using multiyear model output (or any model output for that matter instead of raw data) is so minimal relative to other sources of bias as to be something we should totally ignore. I feel pretty damn strongly about this having had a chance to look under the hood at more salmon abundance estimates than most folks and know just how bad it is. A common example would be folks reporting an estimate as a "total" when they missed half the trapping season prior to the advent of the multiyear model. The obvious bias in that approach is far worse than the bias through shrinkage in a multiyear model.

**Comment by ebuhle** [comment]
> An alternative approach to accounting for (some) sampling uncertainy would be to use the estimates of uncertainty from the "p-spline" model that are generated for all days. Currently, (I believe) estimates of uncertainty are only included from missing trap days and assumed zero on all other days even if sub-sampling occurred. I realize this method isn't totally transferable but it would be a pretty simple way to include some additional observation error as the model is already set up and I'm pretty sure these results could be summarized relatively quickly.

So basically treat subsampling days as missing and use the P-spline to interpolate them? Hm, maybe worth exploring to see how much it changes the CV of the total. (Even if it is throwing away the information in the subsampling estimate.)

> I also have draft versions of a new single year model cooked up in STAN to eventually replace BTSPAS but haven't had time to fully debug them.

I wonder how similar this is to Sorel's single-year BTSPAS replacement, which I believe he ported from my Stan code to TMB. It's in that above-linked repo, but I've only sorta looked at because I only sorta know TMB (just like I only sorta knew ADMB). Might be worth joining forces. I don't think his model deals with the timing of outmigration of marked fish either, although we have talked about it so he may have tackled it since I last checked.

> But I guess my point here is that the bias (as in bias-variance tradeoff) imposed by using multiyear model output (or any model output for that matter instead of raw data) is so minimal relative to other sources of bias as to be something we should totally ignore.

I think I see what you mean by "bias" (or "shrinkage toward a model"), but in terms of estimators I think it's a matter of both bias and (co)variance. I mean, if @kalebentley's example is even close to the true posterior (which it may not be; `n_eff` of 50 is either a very short run or a clear sign of trouble) then that would suggest the annual estimates are strongly correlated. I agree it's not worth worrying about in a data set where 2-4 observations come from multi-year models, but I wouldn't discount it entirely.

> I feel pretty damn strongly about this having had a chance to look under the hood at more salmon abundance estimates than most folks and know just how bad it is. A common example would be folks reporting an estimate as a "total" when they missed half the trapping season prior to the advent of the multiyear model. The obvious bias in that approach is far worse than the bias through shrinkage in a multiyear model.

Oh, without a doubt. Talk about a low bar!
