### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by mdscheuerell** [mdscheuerell/chumIPM#23]
The repo's [README](https://github.com/mdscheuerell/chumIPM#readme) points to a vignette that's 5 years old. Perhaps it should be updated to the version @ebuhle recently pushed [here](https://github.com/mdscheuerell/chumIPM/blob/master/analysis/R/LCRchumIPM_analysis.html)?

**Comment by ebuhle** [comment]
Good point; I never even look at the landing page. I updated the link in 6f0ea67ae9926caf66612c36872ec689e9e52f69, but since it's just a raw HTML rather than a website, the reader would have to download it. Sometime in the not-too-distant future I'll have to learn how github.io works, so we can revisit this then.
